name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run:  sh ./configure.sh
    - name: Build lib
      run: cargo build
    - name: Build examples
      run: cargo build --examples
